version: "3"

tasks:
  bump:
    desc: bump version from version file
    cmds:
      - echo $(cat version | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g') > version.next
      - mv version.next version

  build:
    desc: dockerize the app
    cmds:
      - docker build -t ghcr.io/silenteer/proxier:$(cat version) .

  push:
    desc: push image to docker
    cmds:
      - docker push ghcr.io/silenteer/proxier:$(cat version)
      - docker tag ghcr.io/silenteer/proxier:$(cat version) ghcr.io/silenteer/proxier:latest
      - docker push ghcr.io/silenteer/proxier:latest

  release:
    desc: bump, build and release
    cmds:
      - task: bump
      - task: build
      - task: push
